name: SoraTalk-V2
description: "SoraTalk：夥伴的日語會話隨身教室"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # 這是確保括號排版在 Web 上美觀的關鍵
  google_fonts: ^8.0.2
  flutter_tts: ^4.2.5
  record: ^6.2.0
  audioplayers: ^6.6.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true